name: GitHub Snake

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate SVG images
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-snake.svg?palette=github-light
            dist/github-contribution-snake-dark.svg?palette=github-dark
      - name: Push images to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
